Controllers films users
Ovarbor/java-filmorate pull request #2
Opened 2022-09-09 21:24 UTC by Ovarbor

Финальное задание 9

2022-09-10 17:59 UTC, andrew-larkin requested changes
Привет! В целом, очень хорошая реализация, но нужно немного доработать: 
1) добавить валидацию для полей класса в папке model;
2) убрать излишние проверки входных данных в контроллерах (либо посредством валидации, либо перенеся функционал проверок в отдельный класс);
3) немного поправить тесты. Они кстати, очень даже неплохо написаны.
Это поправить и работа будет принята.

2022-09-10 17:59 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
достаточно добавить аннотацию @Slf4j к классу - она добавит логгирование от ломбока

2022-09-10 17:59 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/fimorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isBlank()) {
все проверки лучше вынести либо в отдельный метод, либо в отдельный класс.

2022-09-10 17:59 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/fimorate/model/Film.java
> +public class Film {
стоит попробовать использовать валидацию от спринга - она уберет необходимость проверок в контроллере

2022-09-10 17:59 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/fimorate/model/User.java
> +public class User {
стоит попробовать использовать валидацию от спринга - она уберет необходимость проверок в контроллере. Для каждого поля в этом классе можно добавить соответсвующую аннотацию, которая не позволит создавать объекты класса с невалидными данными

2022-09-10 17:59 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/fimorate/FilmControllerTest.java
> +    MockMvc mockMvc;
в тестах для внедряемых объектов стоит использовать модификатор доступа private

2022-09-10 17:59 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/fimorate/UserControllerTest.java
> +    MockMvc mockMvc;
в тестах для внедряемых объектов стоит использовать модификатор доступа private

2022-09-10 17:59 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/fimorate/FilmControllerTest.java
> +    Film film1 = new Film("film1", "film1", LocalDate.of(2001, Month.AUGUST, 13), 60);
создание тестовых данных стоит вынести в метод с аннотацией @BeforeEach, например, либо просто в отдельный приватный метод

2022-09-10 17:59 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/fimorate/UserControllerTest.java
> +    User user = new User("1111@gmail.com", "newlogin", "newname", LocalDate.of(2001, Month.AUGUST, 13));
аналогично как и для FilmControllerTest

2022-09-11 09:33 UTC, Ovarbor commented on src/main/java/ru/yandex/practicum/fimorate/model/Film.java
> +public class Film {
исправлено

2022-09-11 09:33 UTC, Ovarbor commented on src/main/java/ru/yandex/practicum/fimorate/model/User.java
> +public class User {
исправлено

2022-10-08 07:53 UTC, merged